language: generic

matrix:
  include:
    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil
        - DOCKERTAG=latest

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil
        - DOCKERTAG=jnlp-slave

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-comp7
        - DOCKERTAG=latest

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-comp7
        - DOCKERTAG=jnlp-slave
      
    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-ppc64le
        - DOCKERTAG=latest

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-aarch64
        - DOCKERTAG=latest

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=9.2
        - CUDA_VER=9.2

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=10.0
        - CUDA_VER=10.0

env:
  global:
    secure: "nM8OaFilQkH14wzD1S6DTGejjo3yL/q/1dpz7144Kw68s8FVqW0zsxCC6960ieokY2LutGSv16qTiIFxnRZnHPCXt7X2MhxcagX8IcMu62DWe2jgqwho0hPI65N/bQYLW1l23e9tjKQxWFZopM4Oyzm6TBqlzibTdbPuQI+YB3RBY0dlkIlupPIYtiNlLRR/HnOyyUny/hg3Z65GWeVpXhiMPqXLlfliTiQ31JgBaNuXiP3/ruSCDeyRPWx62IcPGJ1xVSXL3tvkEI2TpGVCsraKCSbgINhm3AHjQ+8ST6GPMxaOaHrKZzssKJpsZhz1dzWINXTLOQ5LrKtBVwfaevFxDmPEr9RcVlzwAAyuWugCyV4Z6NSt/j2Qqw5qGaiiDHyBH0FMmBgzlPzLZ4JKFsZ68aRkc2qV0MeN0YJRwcQ0EnXRULrcwReBztDHZwixSxqlPpQUwbRr7ne05rBjVoMTKaEhyHPO+KYSwQB1wiQgILBtlP/5ofsYc9Eb46m5JJJhJxuLythKpW9mMqd/US4rQrgEHQ/QRIRYwzGnKf/5WXV3W2o4C9QZpH5Da3J7jOLlqxIY5I+Dv9eEk7XxhT7UaEo7C9tmzjaL2D0yrzPnOnPQhMpmCVNWqdTp1eLcIASKSPbmzz8MuYB5yg48wjXWvDIRBQ6hJyuKHhNGE9k="

before_install:
    # Enable experimental features (needed for squash)
    - sudo cp docker_daemon_config.json /etc/docker/daemon.json
    - sudo service docker restart

    - docker info
    - |
      if [ "$(uname -m)" = "x86_64" ]; then
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      fi
      export QEMU_STATIC_VERSION=v3.1.0-2
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-ppc64le-static
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-aarch64-static
      chmod +x qemu-ppc64le-static
      chmod +x qemu-aarch64-static

install:
    - |
      if [[ $DOCKERTAG == "jnlp-slave" ]]
      then
        sed "s|@BASE_IMAGE@|condaforge/${DOCKERIMAGE}|" jnlp-slave/Dockerfile.in > $DOCKERIMAGE/Dockerfile
      fi
    - docker build --build-arg CUDA_VER -t condaforge/$DOCKERIMAGE:$DOCKERTAG -f $DOCKERIMAGE/Dockerfile --no-cache --squash .

script:
    - |
      if [[ $DOCKERTAG != "jnlp-slave" ]]
      then
        ./.circleci/run_docker_build.sh
      fi

deploy:
  provider: script
  script: docker login -u condaforgebot -p $DH_PASSWORD && docker push condaforge/$DOCKERIMAGE:$DOCKERTAG
